// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3LE-FYHLVu3CSsZ8puUCNDoL5SY4hyM',
    appId: '1:445521953017:web:fc6fa895321641ee0e6228',
    messagingSenderId: '445521953017',
    projectId: 'caresnap-app',
    authDomain: 'caresnap-app.firebaseapp.com',
    storageBucket: 'caresnap-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcIcQU9nljtn6tD_rO9Uqt0iJnMbTdJ8',
    appId: '1:445521953017:android:f90d14b0d05bd95a0e6228',
    messagingSenderId: '445521953017',
    projectId: 'caresnap-app',
    storageBucket: 'caresnap-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE8hQMd43S15-8HXxkXsyfJWUITrQAJRg',
    appId: '1:445521953017:ios:204d955409dfdaea0e6228',
    messagingSenderId: '445521953017',
    projectId: 'caresnap-app',
    storageBucket: 'caresnap-app.firebasestorage.app',
    iosBundleId: 'com.example.caresnap',
  );
}
